---
title: "Imagen Covid"
author: "Sergio Martín, Sergio Cabral y Diego Camacho"
date: "2023-03-07"
output: html_document
---

Primero cargamos las librerías necesarias para hacer el trabajo
```{r}
library(ggplot2)
library(readr)
```

Ahora cargamos el paquete de datos necesario que estará en la carpeta del proyecto
```{r}
d <- read_csv("owid-covid-data.csv")
```

Ahora haremos la gráfica pedida con las funciones de ggplot2

Empezamos seleccionando los países que utilizaremos en la gráfica
```{r}
Japan <- d[d$location == "Japan", ]
Canada <- d[d$location == "Canada", ]
Germany <- d[d$location == "Germany", ]
France <- d[d$location == "France", ]
US <- d[d$location == "United States", ]
Italy <- d[d$location == "Italy", ]
UK <- d[d$location == "United Kingdom", ]
Spain <- d[d$location == "Spain", ]

paises <- rbind(Japan, Canada, Germany, France, US, Italy, UK)
```

Procedemos a hacer el gráfico
```{r}
c <- ggplot(paises, aes(x = date, y = new_deaths_smoothed_per_million, group = location, color = location)) + geom_line()

c1 <- geom_line(data = Spain, aes(x = date, y = new_deaths_smoothed_per_million), color = 'black', size = 1.3)

c2 <- labs(title = 'Muertes Covid-19 por países (España aparece en negro y más grande)', subtitle ='La gráfica muestra las muertes por cada millón de personas provocadas en ciertos países por el Covid', y = 'Muertes por milón de personas', x = 'Fecha')

grafica <- c + c1 + c2
grafica
```

